[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git diff --quiet HEAD^ HEAD -- . ':!README.md' ':!**/*.md'"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--prefer-offline --no-audit --no-fund"

# HTML sem cache
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"

# Imagens: cache agressivo
[[headers]]
  for = "/assets/*.{png,jpg,jpeg,webp,avif,svg,ico}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# CSS/JS: cache mas **sem** immutable
[[headers]]
  for = "/assets/*.{css,js}"
  [headers.values]
    Cache-Control = "public, max-age=604800"

# Segurança base
[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"


# Pretty URLs (com e sem barra)
[[redirects]]
  from = "/consultoria"
  to = "/consultoria.html"
  status = 200
[[redirects]]
  from = "/consultoria/"
  to = "/consultoria.html"
  status = 200

[[redirects]]
  from = "/contato"
  to = "/contato.html"
  status = 200
[[redirects]]
  from = "/contato/"
  to = "/contato.html"
  status = 200

[[redirects]]
  from = "/gestao"
  to = "/gestao.html"
  status = 200
[[redirects]]
  from = "/gestao/"
  to = "/gestao.html"
  status = 200

[[redirects]]
  from = "/politica-de-privacidade"
  to = "/politica-de-privacidade.html"
  status = 200
[[redirects]]
  from = "/politica-de-privacidade/"
  to = "/politica-de-privacidade.html"
  status = 200

[[redirects]]
  from = "/solucoes"
  to = "/solucoes.html"
  status = 200
[[redirects]]
  from = "/solucoes/"
  to = "/solucoes.html"
  status = 200
