[build]
  command = "npm run build"
  publish = "dist"

# HTML sem cache forte
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"

# Assets com cache agressivo
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Pretty URLs (com e sem barra)
[[redirects]]
  from = "/consultoria"
  to = "/consultoria.html"
  status = 200
[[redirects]]
  from = "/consultoria/"
  to = "/consultoria.html"
  status = 200

[[redirects]]
  from = "/contato"
  to = "/contato.html"
  status = 200
[[redirects]]
  from = "/contato/"
  to = "/contato.html"
  status = 200

[[redirects]]
  from = "/gestao"
  to = "/gestao.html"
  status = 200
[[redirects]]
  from = "/gestao/"
  to = "/gestao.html"
  status = 200

[[redirects]]
  from = "/politica-de-privacidade"
  to = "/politica-de-privacidade.html"
  status = 200
[[redirects]]
  from = "/politica-de-privacidade/"
  to = "/politica-de-privacidade.html"
  status = 200

[[redirects]]
  from = "/solucoes"
  to = "/solucoes.html"
  status = 200
[[redirects]]
  from = "/solucoes/"
  to = "/solucoes.html"
  status = 200
